version: '3.8'

services:
  # Edwards Group Holdings Website
  website:
    build: .
    container_name: egh-website
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      # Mount CSV files for live editing during development
      - ./newspapers.csv:/usr/share/nginx/html/newspapers.csv:ro
      - ./radio_networks.csv:/usr/share/nginx/html/radio_networks.csv:ro
      - ./printing_companies.csv:/usr/share/nginx/html/printing_companies.csv:ro
      - ./leadership.csv:/usr/share/nginx/html/leadership.csv:ro
      - ./corporate_office.csv:/usr/share/nginx/html/corporate_office.csv:ro
    networks:
      - egh-network
    labels:
      - "project=egh-website"
      - "environment=development"

  # Development tools container
  dev-tools:
    image: alpine:latest
    container_name: egh-dev-tools
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - egh-network
    command: tail -f /dev/null  # Keep container running
    profiles:
      - dev-tools
    labels:
      - "project=egh-website"
      - "environment=development"

networks:
  egh-network:
    driver: bridge
    labels:
      - "project=egh-website"

volumes:
  egh-data:
    driver: local
    labels:
      - "project=egh-website"